### ISSUE TITLE
Does not respond to HDMI-CEC playback controls

### ISSUE THREAD

**Issue by LinAGKar** [jellyfin/jellyfin-chromecast#364] opened 2022-03-31 07:06 UTC
**Describe the bug**

Jellyfin on Chromecast does not respond to playback controls on the TV remote, sent over HDMI-CEC

**To Reproduce**

1. Play something from Jellyfin on Chromecast
2. Make sure CEC is connected
3. Press pause on the TV remote

**Expected behavior**

The video pauses

**System:**

-   OS: Docker
-   Jellyfin Version: 10.8.0-beta1
-   Cast client: gen 2

**Comment by neopc10** [comment] 2022-08-02 13:36
#53

**Comment by BloodyIron** [comment] 2023-08-08 02:00
> #53

How exactly is that relevant? I don't see CEC mentioned once. Is this still the case of it being broken @LinAGKar ?

**Comment by LinAGKar** [comment] 2023-08-14 17:53
Nothing seems to have changed. Stable Chromecast still doesn't respond to CEC, unstable Chromecast still doesn't work at all

**Comment by cvium** [comment] 2023-08-14 17:55
We're unfortunately in dire need of a maintainer for the CC client. The active members of the Jellyfin team do not use CC, so there's little incentive.

**Comment by daprahamian** [comment] 2024-02-26 02:02
IS there any way I could help get this moving? I'm not super experienced with the ecosystem, but I use almost exclusively Chromecast and would like to be able to control playback with my TV remote. This issue combined with https://github.com/jellyfin/jellyfin-web/issues/3541 means that I frequently wind up in a situation where video is playing on my TV and I have no way to pause it.

**Comment by nielsvanvelzen** [comment] 2024-02-26 07:40
The only way to get it moving is to fix the bug yourself or find someone to do it. We don't have any contributors for casting support right now.

**Comment by nielsvanvelzen** [comment] 2024-04-11 15:54
Closing as duplicate of #53.

I'd also like to remind everyone that we currently do not have any contributors for the cast receiver.

**Closed by nielsvanvelzen** 2024-04-11 15:54 UTC
Labels: bug

**Comment by 3flex** [comment] 2024-10-10 08:36
This should be reopened, it's distinct from #53 - this was mentioned above, and the HDMI-CEC issue is still present.
