### ISSUE TITLE
Progress bar constantly visible obscuring playback

### ISSUE THREAD

**Issue by rsniezek** [jellyfin/jellyfin-chromecast#349] opened 2021-12-07 19:54 UTC
I recently started to suffer from annoying issue that makes JF unusable for me.

When casting video from my local network server to a Chromecast device, the progress bar at the bottom of the screen, the one with poster, tittle and playback position, never hides itself, remains constantly visible (and the playback position is not being updated with time), obscuring about 20% of screen area, including subtitles.

It doesn't matter if I first connect to Chromecast and then select the media, or if I switch to casting during the playback in my phone.

I have server on Raspberry Pi 4B, connected via stable Ethernet to local router, to which also my Chromecast is connected, on the same local network. I use android app for control.

Steps to reproduce:
1. Start playback is any video on Chromecast
2. Wait for it to start playing

Expected result:
Video playback starts, progress bar disappears after few seconds.

Actual results:
Video playback starts, progress bar is constantly visible obscuring screen.

JF Server version 10.7.7, android app version 2.4.2
Raspberry pi 4b, 4gb version running raspberry pi os bullseye. Jellyfin installed from repositories.

**Comment by snieguzary** [comment] 2021-12-08 20:06
Can someone at least point me to an example of code that displays or hides the progress bar? I could debug this more but I have zero knowledge on the code base

**Comment by dejhost** [comment] 2022-09-19 19:24
Same here. I am accessing jellyfin (Version: 10.8.4, Operating System: Linux, 
Architecture: X64, Docker-Compose) through the web-interface using my Vivaldi-Browser, casting to chromecast. The progressbar and movie-titles won't disappear. Same thing happens when I access the jellyfin-server using myAndroid-App (v. 2.4.4) and cast to the chromecast. But I don't think it's something that can a fixed by setting, is it? It's a bug...

**Comment by gazhay** [comment] 2023-03-10 13:34
Same here, intermittently happens on chrome on linux for me.

**Comment by TNieuwdorp** [comment] 2023-12-31 14:41
I feel it's related to subtitles. It happens if a stream starts with subtitles. If I start it without, and then load the subtitles, it disappears as it should...

**Comment by itsthejoker** [comment] 2024-01-08 21:10
Same issue as https://github.com/jellyfin/jellyfin-chromecast/issues/16

**Comment by nielsvanvelzen** [comment] 2024-01-08 21:14
Thanks, closing as duplicate of #16.

**Closed by nielsvanvelzen** 2024-01-08 21:14 UTC
