### ISSUE TITLE
chromecast reciever controller playback options

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-chromecast#346] opened 2021-10-09 23:20 UTC
**Describe the feature you'd like**
i would like to see forward/backward skips, pause/resume options at the chromecast reciever so i can use the chromecast remote controller instead of my mobile phone to do the things :)

**Additional context**
is these even possible?

**Comment by nielsvanvelzen** [comment] 2024-04-11 15:54
Closing as duplicate of #53.

I'd also like to remind everyone that we currently do not have any contributors for the cast receiver.

**Closed by nielsvanvelzen** 2024-04-11 15:54 UTC
