### ISSUE TITLE
Wrong state reported on google cast. (Always idle)

### ISSUE THREAD

**Issue by maxi1134** [jellyfin/jellyfin-chromecast#372] opened 2022-07-13 21:30 UTC
**Describe the bug**

The state of the player playing jellyfin is always Idle

**To Reproduce**

Start a stream on a Chromecast device and monitor it on a tool like Home-Assistant or using pycast.

**Expected behavior**

The state should reflect what is happening on the chromecast.

Paused/Playing/Buffering/Idle/Off

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/1342643/178839718-61aeb174-dd1d-479f-bca6-dd8c125f8b88.png)

**System (please complete the following information):**

-   OS: Ubuntu 20.04 Installed with APT
-   Browser: Chrome 
-   Jellyfin Version: 10.8.1
-   Cast client: Chromecast Ultra

**Additional context**

Additionally, the name of the episode/movie playing should be reflected as well.

**Comment by Parley1984** [comment] 2022-08-02 10:15
English: I can confirm the problem. The status of the Chromecast is always Idle. Regardless of whether something is running or not. 

German: Das Problem kann ich bestätigen. Der Status des Chromecast ist immer Idle. Unabhängig ob etwas läuft oder nicht.

**Comment by Parley1984** [comment] 2022-08-02 13:32
Update: Set the Chromecast version to unstable in the playback settings of Jellyfin. After that, everything will be displayed correctly in home assistant.

**Comment by neopc10** [comment] 2022-08-02 13:36
#53

**Comment by theclue** [comment] 2024-04-11 14:59
Resurfacing this old thread to point out that I've the same behaviour (test made using Home Assistant and a Sony Bravia TV). State is dangling to 'idle' indefinitively.

Additionally, even if I go back to the TV home page, 'Jellyfin' still stays as media_name

Setting the Chromecast version to 'unstable' didn't solve the issue.

**Comment by maxi1134** [comment] 2024-04-11 15:43
I confirm that unstable version does not work go rme either.

**Comment by nielsvanvelzen** [comment] 2024-04-11 15:54
Closing as duplicate of #53.

I'd also like to remind everyone that we currently do not have any contributors for the cast receiver.

**Closed by nielsvanvelzen** 2024-04-11 15:54 UTC
Labels: bug

**Comment by maxi1134** [comment] 2024-04-11 15:58
> I'd also like to remind everyone that we currently do not have any contributors for the cast receiver.

Thank you for this piece of information! I'll keep using plex until this changes.

God speed!

**Comment by WillT93** [comment] 2025-05-15 11:35
Sadly, I just spent the day renaming my Plex library to the Jellyfin standard in an effort to move over. But this is a deal breaker for me as it breaks a series of automations I have set up to trigger off these states.

Like others, I'll have to stay with Plex for now.
